//! Application orchestration layer for Hobit.
//!
//! This crate composes lower-level storage primitives into product-level use
//! cases. It does not expose frontend integration directly; desktop/Tauri
//! exposure is added in the desktop shell crate.

#![forbid(unsafe_code)]

pub mod artifacts;
pub mod audit_events;
pub mod capabilities;
pub mod context_packs;
mod error;
pub mod knowledge;
pub mod runtime_adapters;
mod workspace_service;

pub use artifacts::{
    ArtifactContentClass, ArtifactContextEligibility, ArtifactCoordinatorProposalRef,
    ArtifactDirectWorkRunRef, ArtifactEvidenceEligibility, ArtifactExternalSourceRef,
    ArtifactGitCommitRef, ArtifactGitDiffRef, ArtifactGitStatusRef, ArtifactId,
    ArtifactJdbcQueryRef, ArtifactJdbcResultRef, ArtifactNoteRef, ArtifactOrigin,
    ArtifactOwnerKind, ArtifactOwnerRef, ArtifactQueueTaskRef, ArtifactRef, ArtifactRefSummary,
    ArtifactResolutionStatus, ArtifactRetentionHint, ArtifactSensitivity, ArtifactSourceRef,
    ArtifactStorageKind, ArtifactTerminalRunRef, ArtifactTerminalSessionRef, ArtifactVisibility,
    ArtifactWidgetDefinitionRef, ArtifactWidgetInstanceRef, ArtifactWidgetLogRef,
    ArtifactWidgetResultRef, ArtifactWidgetRunRef, ArtifactWorkbenchRef, ArtifactWorkspaceRef,
};
pub use audit_events::{
    AuditActionRef, AuditActorKind, AuditActorRef, AuditApprovalId, AuditApprovalRef,
    AuditApprovalStatus, AuditArtifactId, AuditArtifactRef, AuditCapabilityRef, AuditCausationId,
    AuditCorrelationId, AuditErrorClass, AuditEventEnvelope, AuditEventId, AuditEventKind,
    AuditEventSummary, AuditOrganizationRef, AuditRiskLevel, AuditRunRef, AuditSchemaVersion,
    AuditTaskRef, AuditWidgetDefinitionRef, AuditWidgetInstanceRef, AuditWidgetRef,
    AuditWorkbenchRef, AuditWorkspaceRef,
};
pub use capabilities::{
    CapabilityActionCausation, CapabilityActionCorrelation, CapabilityActionId,
    CapabilityActionKind, CapabilityActionLifecycleStatus, CapabilityActionRef,
    CapabilityActionSummary, CapabilityActorId, CapabilityActorKind, CapabilityActorRef,
    CapabilityApprovalDecision, CapabilityApprovalRef, CapabilityApprovalRequirement,
    CapabilityArtifactPolicy, CapabilityBoundarySummary, CapabilityContextExposure,
    CapabilityExecutionMode, CapabilityExternalAccess, CapabilityId, CapabilityKind,
    CapabilityMutationScope, CapabilityRiskLevel, CapabilitySecretExposure, CapabilitySubjectRef,
    CapabilitySummary, CapabilityWidgetDefinitionRef, CapabilityWidgetInstanceRef,
    CapabilityWorkbenchRef, CapabilityWorkspaceRef, WidgetCapabilityRef, WorkspaceCapabilityRef,
};
pub use context_packs::{
    ContextPackEligibility, ContextPackExternalRef, ContextPackFreshness, ContextPackId,
    ContextPackItemKind, ContextPackItemRef, ContextPackRef, ContextPackReviewStatus,
    ContextPackSelectionReason, ContextPackSensitivity, ContextPackSharingScope,
    ContextPackSummary, ContextPackVisibility,
};
pub use error::WorkspaceServiceError;
pub use hobit_core::widgets::WidgetRunStatus;
pub use hobit_tools::codex_cli::CodexDirectStreamCancellationToken;
pub use knowledge::{
    EvidenceArtifactLink, EvidenceAttribution, EvidenceConfidence, EvidenceFreshness, EvidenceId,
    EvidenceRef, EvidenceReviewStatus, EvidenceSourceId, EvidenceSourceKind, EvidenceSourceRef,
    KnowledgeContextEligibility, KnowledgeContextSnapshot, KnowledgeContextSnapshotContentKind,
    KnowledgeDraftReviewDecision, KnowledgeDraftReviewDecisionKind, KnowledgeEvidenceLink,
    KnowledgeFinderSelectionSourceRef, KnowledgeFreshness, KnowledgeImportFileSourceRef,
    KnowledgeItemId, KnowledgeItemKind, KnowledgeItemRef, KnowledgeItemType,
    KnowledgeLifecycleStatus, KnowledgeManualSourceRef, KnowledgeModelParseError,
    KnowledgeNoteSourceRef, KnowledgeOwnerId, KnowledgeOwnerRef, KnowledgePathSourceRef,
    KnowledgeQueueRunSourceRef, KnowledgeQueueTaskSourceRef, KnowledgeRefSummary,
    KnowledgeRelation, KnowledgeReviewStatus, KnowledgeSafetyWarning,
    KnowledgeSafetyWarningSeverity, KnowledgeScope, KnowledgeSourceRef, KnowledgeVersionSummary,
    KnowledgeVisibility, KnowledgeWorkspaceRef, RunbookId, RunbookRef, SkillId, SkillRef,
    SkillReviewStatus, SkillVersionRef,
};
pub use runtime_adapters::{
    RuntimeAdapterId, RuntimeArtifactClass, RuntimeArtifactSummary, RuntimeCorrelationId,
    RuntimeErrorKind, RuntimeExecutionStatus, RuntimeKind, RuntimeRedactionStatus,
    RuntimeRequestId,
};
pub use workspace_service::{
    coordinator_provider_adapter_from_config, parse_and_preview_agent_queue_prompt_pack,
    AckAgentQueueReviewMessageInput, AgentChatAiProposalProvider, AgentChatAiProposalRunSummary,
    AgentChatAiProviderOutcome, AgentChatAiRequestArtifact, AgentChatProposalActionInput,
    AgentChatProposalInput, AgentChatProposalRunSummary, AgentExecutorDiffFileSummary,
    AgentExecutorDiffSummary, AgentExecutorDiffTotals, AgentExecutorRunDetail,
    AgentExecutorRunHistory, AgentExecutorRunSummary, AgentMonitoringProposalActionSummary,
    AgentMonitoringProposalResultSummary, AgentMonitoringSnapshot,
    AgentQueueCompletionCommandBlocker, AgentQueueCompletionCommandResult,
    AgentQueueCompletionCommandStatus, AgentQueueCompletionDecisionSummary,
    AgentQueueControlCommandBlocker, AgentQueueControlCommandStatus, AgentQueueControlStateSummary,
    AgentQueueFailureCommandBlocker, AgentQueueFailureCommandResult,
    AgentQueueFailureCommandStatus, AgentQueueFailureDecisionSummary, AgentQueueItemSummary,
    AgentQueuePromptPackConstraintsPreview, AgentQueuePromptPackDefaultsPreview,
    AgentQueuePromptPackExecutionTargetPreview, AgentQueuePromptPackFileRequest,
    AgentQueuePromptPackMaterializeRequest, AgentQueuePromptPackMaterializeResult,
    AgentQueuePromptPackMaterializedTaskResult, AgentQueuePromptPackMetadataPreview,
    AgentQueuePromptPackPreview, AgentQueuePromptPackPreviewDiagnostic,
    AgentQueuePromptPackPreviewRequest, AgentQueuePromptPackPreviewResult,
    AgentQueuePromptPackRunSettingsPreview, AgentQueuePromptPackSafetyPreview,
    AgentQueuePromptPackSourceMetadata, AgentQueuePromptPackTaskPreview,
    AgentQueueProposalActionSummary, AgentQueueReviewCommandResult,
    AgentQueueReviewCreateMessageBlocker, AgentQueueReviewCreateMessageResult,
    AgentQueueReviewCreateMessageStatus, AgentQueueReviewMessageSummary, AgentQueueSnapshot,
    AgentQueueTaskRunLink, AgentQueueTaskRunLinkId, AgentQueueTaskRunReviewStatus,
    AgentQueueTaskRunSource, AgentQueueTaskRunStatus, AgentQueueTaskRunSummary,
    AgentQueueTaskSummary, AgentQueueValidationCommandEvidenceSummary,
    AgentQueueValidationCommandRunSummary, AgentQueueValidationCommandSpecInput,
    AgentQueueValidationSuiteRunSummary, AgentQueueWorkerEvidenceBundleSummary,
    AgentQueueWorkerEvidenceQueryResult, AgentQueueWorkerEvidenceQueryState,
    AgentQueueWorkerFinishedCommandResult, AgentQueueWorkerSummary,
    AssignAgentQueueTaskToExecutorInput, AssignedAgentQueueTaskRunPlan,
    AssignedAgentQueueTaskStartSummary, AttachKnowledgeToQueueTaskInput,
    AttachSkillToQueueTaskInput, CancelCodexDirectWorkRunInput, CheckJdbcSidecarHealthInput,
    CheckQueueLocalProviderAuthContextInput, CheckQueueLocalProviderReadinessInput,
    ClearAgentQueueTaskAssignmentInput, CodexDirectWorkCancellationSummary,
    CodexDirectWorkForceKillSummary, CodexDirectWorkRunSummary, CodexDirectWorkStreamEventSummary,
    CodexDirectWorkStreamStartSummary, CoordinatorProviderAdapter, CoordinatorProviderMessage,
    CoordinatorProviderOutcome, CoordinatorProviderProposalDraftContext,
    CoordinatorProviderRequest, CoordinatorProviderResponse, CoordinatorProviderRuntimeConfig,
    CoordinatorProviderVisibleInput, CreateAgentQueueItemFromProposalInput,
    CreateAgentQueueReviewMessageInput, CreateAgentQueueTaskInput, CreateAgentQueueWorkerInput,
    CreateGitCommitInput, CreateJdbcConnectionProfileInput, CreateJdbcConnectorInput,
    CreateKnowledgeDocumentInput, CreateSkillInput, CreateWorkspaceGitCommitInput,
    CreateWorkspaceGitPushInput, CreateWorkspaceNoteInput, DeleteAgentQueueTaskInput,
    DeleteAgentQueueWorkerInput, DeleteJdbcConnectionProfileInput, DeleteKnowledgeDocumentInput,
    DeleteSkillInput, DetachKnowledgeFromQueueTaskInput, DetachSkillFromQueueTaskInput,
    DirectWorkValidationRunSummary, DogfoodOperatorWorkspaceContextSummary,
    ExecuteJdbcReadOnlyQueryInput, ExternalCoordinatorProviderAdapter,
    ExternalCoordinatorProviderConfig, FailAgentQueueItemInput,
    FinishAssignedAgentQueueTaskRunInput, ForceKillCodexDirectWorkRunInput,
    GenerateAgentChatAiProposalInput, GenerateCoordinatorProviderResponseInput,
    GetAgentQueueWorkerEvidenceBundleInput, GitBranchStatusSummary, GitCommitCommandSummary,
    GitCommitRunSummary, GitDiffCommandSummary, GitFileChangeSummary, GitFileDiffSummary,
    GitLastCommitSummary, GitLogEntrySummary, GitLogSummary, GitPushCommandSummary,
    GitPushRunSummary, GitRepositoryStatusSummary, GitWorkingTreeStatusSummary,
    JdbcConnectionProfileSummary, JdbcConnectorSummary, JdbcExperimentalSidecarRuntimeInput,
    JdbcQueryColumnSummary, JdbcReadOnlyQueryResultSummary, JdbcReadOnlySqlValidationSummary,
    JdbcSidecarDiagnosticSummary, KnowledgeDocumentSearchResultSummary, KnowledgeDocumentSummary,
    KnowledgeDraftReviewSummary, ListKnowledgeDraftReviewsInput, MarkAgentQueueItemDoneInput,
    MockCoordinatorProviderAdapter, PersistAgentChatProposalInput, ProbeJdbcDriverInput,
    QueueItemAggregate, QueueItemAggregateBlocker, QueueItemAggregateCommitState,
    QueueItemAggregateDependencyState, QueueItemAggregateDurableFlags,
    QueueItemAggregateEvidenceState, QueueItemAggregateEvidenceSummary,
    QueueItemAggregateLatestRun, QueueItemAggregateNextAction, QueueItemAggregateReviewState,
    QueueItemAggregateRunSettings, QueueItemAggregateTicketState,
    QueueItemAggregateValidationState, QueueItemAggregateWorkerRunState,
    QueueLocalProviderAuthContextSnapshot, QueueLocalProviderAuthContextSummary,
    QueueLocalProviderAuthContextsSummary, QueueLocalProviderEnvironmentSummary,
    QueueLocalProviderReadinessSummary, QueueWorkerStartBlocker, QueueWorkerStartContext,
    QueueWorkerStartSettingsSnapshot, QueueWorkflowAction, QueueWorkflowActionStatus,
    QueueWorkflowApplyRunSettingsRequest, QueueWorkflowApplyRunSettingsResult,
    QueueWorkflowApplyRunSettingsStatus, QueueWorkflowCancelRequest, QueueWorkflowCancelResult,
    QueueWorkflowCancelStatus, QueueWorkflowCommandBlocker, QueueWorkflowConflict,
    QueueWorkflowCreateSetupStartActionSnapshots,
    QueueWorkflowCreateSetupStartDownstreamVerification,
    QueueWorkflowCreateSetupStartQueueControlSnapshot, QueueWorkflowCreateSetupStartStepPlan,
    QueueWorkflowCreateSetupStartStepPlanAction, QueueWorkflowCreateSetupStartStepRequest,
    QueueWorkflowCreateSetupStartStepResult, QueueWorkflowCreateSetupStartStepResultStatus,
    QueueWorkflowCreateSetupStartStepTransition, QueueWorkflowExecutionTarget,
    QueueWorkflowFinalizationBindingSummary, QueueWorkflowFinalizationDownstreamVerification,
    QueueWorkflowFinalizationStepPlan, QueueWorkflowFinalizationStepRequest,
    QueueWorkflowFinalizationStepResult, QueueWorkflowFinalizationStepResultStatus,
    QueueWorkflowFinalizationStepTransition, QueueWorkflowGetRequest, QueueWorkflowListRequest,
    QueueWorkflowMaterializeTaskSlotRequest, QueueWorkflowMaterializeTaskSlotResult,
    QueueWorkflowMaterializeTaskSlotStatus, QueueWorkflowPlanResumeRequest,
    QueueWorkflowPromoteTaskSlotBindingSummary, QueueWorkflowPromoteTaskSlotRequest,
    QueueWorkflowPromoteTaskSlotResult, QueueWorkflowPromoteTaskSlotStatus,
    QueueWorkflowRecordRunnerAction, QueueWorkflowRecordRunnerReportRequest,
    QueueWorkflowRecordRunnerReportResult, QueueWorkflowRecordRunnerReportStatus,
    QueueWorkflowRecordWorkerEvidenceRequest, QueueWorkflowRecordWorkerEvidenceResult,
    QueueWorkflowRecordWorkerEvidenceStatus, QueueWorkflowReport, QueueWorkflowResumeBlocker,
    QueueWorkflowResumePlan, QueueWorkflowResumePlanStatus, QueueWorkflowReviewBindingSummary,
    QueueWorkflowReviewStepPlan, QueueWorkflowReviewStepRequest, QueueWorkflowReviewStepResult,
    QueueWorkflowReviewStepResultStatus, QueueWorkflowReviewStepTransition, QueueWorkflowRun,
    QueueWorkflowRunSettings, QueueWorkflowRunSettingsBindingSummary, QueueWorkflowRunStatus,
    QueueWorkflowSlotReconciliation, QueueWorkflowStartRequest, QueueWorkflowStartResult,
    QueueWorkflowStartStatus, QueueWorkflowTaskResumeSnapshot, QueueWorkflowTaskSlotBindingSummary,
    QueueWorkflowTaskSpec, QueueWorkflowWorkerEvidenceBindingSummary,
    QueueWorkflowWorkerEvidenceStepPlan, QueueWorkflowWorkerEvidenceStepResult,
    QueueWorkflowWorkerEvidenceStepResultStatus, QueueWorkflowWorkerEvidenceStepTransition,
    QueueWorkflowWorkerLaunchDisposition, QueueWorkflowWorkerLaunchIntent,
    RecordAgentQueueTaskRunFinalStatusInput, RecordAgentQueueTaskRunStartedInput,
    RecordAgentQueueWorkerFinishedInput, RecordKnowledgeDraftReviewInput,
    RunAgentQueueValidationSuiteInput, RunCodexDirectWorkInput, RunDirectWorkValidationInput,
    RunTerminalCommandInput, SearchKnowledgeDocumentsFiltersInput, SearchKnowledgeDocumentsInput,
    SelectedAgentQueueTaskLocalStartSummary, SetAgentQueueControlStateInput,
    SetAgentQueueControlStateResult, SharedStateObjectSummary, SkillSummary,
    StartAssignedAgentQueueTaskInput, StartSelectedAgentQueueTaskLocalInput,
    TerminalCommandRunSummary, UpdateAgentQueueTaskInput, UpdateAgentQueueWorkerInput,
    UpdateJdbcConnectionProfileInput, UpdateJdbcConnectorInput, UpdateKnowledgeDocumentInput,
    UpdateSkillInput, UpdateWorkspaceNoteInput, ValidateJdbcReadOnlySqlInput, WidgetInstanceLayout,
    WidgetInstanceSummary, WidgetLogSummary, WidgetResultSummary, WidgetRunCommandInput,
    WidgetRunResultInput, WidgetRunSummary, WidgetRunWithResultsSummary, WorkbenchEventSummary,
    WorkbenchSummary, WorkspaceDeletionSummary, WorkspaceNoteSummary, WorkspaceService,
    WorkspaceSessionSummary, WorkspaceSummary, WorkspaceWorkbenchState,
    AGENT_QUEUE_ACCEPTED_COMPLETION_CONFIRMATION_TOKEN, AGENT_QUEUE_COMPLETION_DECISION_ACCEPTED,
    AGENT_QUEUE_CONTROL_STATUS_DISABLED, AGENT_QUEUE_CONTROL_STATUS_MANUAL_ENABLED,
    AGENT_QUEUE_FAILURE_CONFIRMATION_TOKEN, AGENT_QUEUE_FAILURE_DECISION_FAILED,
    EXTERNAL_COORDINATOR_PROVIDER_KIND, MAX_WORKFLOW_ACTION_LOG_SUMMARY_JSON_BYTES,
    MAX_WORKFLOW_GRANT_SUMMARY_JSON_BYTES, MAX_WORKFLOW_IDEMPOTENCY_KEYS_JSON_BYTES,
    MAX_WORKFLOW_INPUTS_JSON_BYTES, MAX_WORKFLOW_MUTATION_REFS_JSON_BYTES,
    MAX_WORKFLOW_SLOT_BINDINGS_JSON_BYTES, MAX_WORKFLOW_VARIABLES_JSON_BYTES,
    QUEUE_LOCAL_BACKEND_EXECUTION_TARGET_ID, QUEUE_LOCAL_BACKEND_WORKBENCH_ID,
};
